language: cpp
sudo: required
dist: focal

os:
  - linux
#  - osx

before_install:
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]];then sudo apt-get -qfy install --no-install-recommends curl ca-certificates
           && curl -sS https://apertium.projectjj.com/apt/install-nightly.sh | sudo bash && sudo apt-get install -qfy  --no-install-recommends build-essential autoconf automake autotools-dev bison flex libicu-dev libreadline-dev libtool pkg-config python3-dev python3-setuptools swig zlib1g-dev libfst-dev libfoma-dev; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]];then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]];then brew install --force bison flex icu4c glib swig python; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]];then export "PATH=$(brew --prefix bison)/bin:$(brew --prefix icu4c)/bin:$PATH"; fi

script:
  - autoreconf -fvi
  - ./configure --disable-static --enable-all-tools --with-readline --with-unicode-handler=icu --with-openfst-upstream --with-foma-upstream --enable-python-bindings
  - make -j4 V=1 VERBOSE=1
  - make check V=1 VERBOSE=1
  - sudo make install

notifications:
    irc:
        channels:
            - secure: "ZTx3qhKDRKG/HHNZVNI1XTW2jVJbQ2X/ZOMW1cTmQV9nGqqdE8uZAEKbYV+s1bydt/Kg/18B9NI1gK3az8r9ZbYLje74KvcwDmI/6T+Xz7m89GKB2B024NUiyx15RmCNjKohsZ+tuTNtZq/sSRSMtTNfoQLYGBzXwqtxbqQmOlU054komGTo+OFrseXv+1t9Qju8qNUirE8NxhTCCVhh57dwPylbFdmxnN5b1rM7qF8O7nmnbav9SZwajn3GFCUj7YSGIfGkMh3I6zyz/iTjKkD5sCKdUQ33A1spX2Evh6IdmJdqTUGMrtozarYBuFMUPYfGByNT4hOkC+Uy32x+1XlQz0chGGQ40Fsuh2Ke4PP52juaZMua+JVsSCel3vOLWkLueAwrymqEu3e65sLErsX+IASV8DkGlpiIXKp0L1hbQ/wQdreGxGsipA2oN4e9dK7jha5uIrZVTpxbijlwkUSLT7s6RRW3HOJQZkGeWcsVz6F7lYTMTqTrrw26/A2pAyuyLR+uPCRItiNzToczMGK/TiMftzQTepST5S1KHM1brJoiyQc1m59+EN6fgVD0j0piADjvdT3isPiZ4AS0t8W6HKEA5ZbXRp+6PTk2iwrEjk/QllxU15RSvUplV4MaNK0bYZUhlL+Slv0WAajQ0zaO6HpZdMV1rg0rPCn7SVM="
        on_failure: always
        on_success: never
# The irc channel is encrypted for hfst/hfst, so build notifications from forks won't show up on the IRC channel
# Encrypt with:
# $ gem install --user-install travis
# $ ~/.gem/ruby/*/bin/travis encrypt -r hfst/hfst 'irc.oftc.net#hfst'
